name: Code Quality

on:
  push:
    branches:
      - kitsune
      - dev
  pull_request:
    branches:
      - kitsune
      - dev
  workflow_dispatch:

jobs:
  kotlin-lint:
    name: Kotlin Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run lint
        run: ./gradlew lint app:lint stub:lint

      - name: Upload lint reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-reports-${{ github.sha }}
          path: |
            **/build/reports/lint-results*.html
            **/build/reports/lint-results*.xml
          compression-level: 9
